name: Generate Snake GIF

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "18"

      # 👇 여기서 자동 설치됨 (로컬 필요 없음)
      - name: Install dependencies
        run: npm install puppeteer gifencoder canvas

      - name: Generate GIF
        run: node generate_gif.js

      - name: Commit GIF
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add assets/preview.gif
          git commit -m "update gif" || echo "no change"
          git push
